# https://taskfile.dev

version: "3"

vars:
  FASTLANE: bundle exec fastlane

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  install:
    desc: Install dependencies
    cmds:
      - bundle install

  match-fetch-development:
    cmds:
      - "{{.FASTLANE}} match_fetch_development"

  register-device:
    cmds:
      - "{{.FASTLANE}} register_a_new_device"
    env:
      DEVICE_NAME: '{{.DEVICE_NAME| default ""}}'
      DEVICE_UDID: '{{.DEVICE_UDID| default ""}}'
      DEVICE_PLATFORM: '{{.DEVICE_PLATFORM| default "ios"}}'

  test:
    cmds:
      - "{{.FASTLANE}} test"

  build-and-distribute-to-testflight:
    cmds:
      - "{{.FASTLANE}} build_and_distribute_to_testflight"
